name: Java Build and Deploy Pipeline

on:
  push:
     branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  # 1: Build - tests ##
  build:
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/build-pipeline.yml@main
   secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #2: Deploy to Docker ##
  deploy-docker:
   needs: build
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/docker-deploy.yml@main

  #3: Deploy to azure ##
  deploy-azure: 
    needs: deploy-docker
    uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/azure-deploy.yml@main
   
   
  